# Tell Travis you want a Python environment to test in
language: python
# List the versions of Python you'd like to test against
python:
  - "2.5"
  - "2.6"
  - "2.7"
# Tell it the things it will need to install when it boots
install: 
 - python setup.py install
script: python test.py
