# Tell Travis you want a Python environment to test in
language: python
# List the versions of Python you'd like to test against
python:
 - "2.6"
 - "2.7"
 - "3.2"
 - "3.3"
# Tell it the things it will need to install when it boots
install: 
 - pip install -r requirements.txt
script: 
 - pep8 la_metro
 - pyflakes la_metro
 - coverage run test.py
after_success:
  - coveralls
